export interface I18nLanguage {
  code: string;
  title: string;
  autogenerated: boolean;
}

export const getMessages = (): { [p: string]: any } => {
  const modules = import.meta.glob('./locales/*.json', { eager: true });

  return Object.fromEntries(
    Object.entries(modules)
      .filter(([key]) => !key.includes('languages.json'))
      .map(([key, value]: [string, any]) => [
        // @ts-expect-error Expect to have only .json files
        key.match(/([^/]+)\.json$/)[1] || '',
        value.default,
      ]),
  );
};

export const getLanguages = (): I18nLanguage[] => {
  const languages: any = import.meta.glob(
    './locales/languages.json',
    { eager: true },
  );
  return languages['./locales/languages.json'].default;
};
