{{- if and .Values.rbac.create .Values.rbac.clusterAdministrator }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "velero-ui.fullname" . }}
  labels:
        {{- include "velero-ui.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "velero-ui.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterAdministratorName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
