{{- if and .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "velero-ui.fullname" . }}
  labels:
    {{- include "velero-ui.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups: ["velero.io"]
    resources: ["*"]
    verbs:
      - "*"
{{- end }}
