{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "velero-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "velero-ui.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
    - "secrets"
  verbs:
    - "get"
    - "watch"
    - "list"
- apiGroups:
    - "velero.io"
  resources:
    - "*"
  verbs:
    - "*"
{{- end }}
