{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "velero-ui.fullname" . }}-permissions
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "velero-ui.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources:
      - pods/log
      - pods/status
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "velero-ui.fullname" . }}-velero-permissions
  namespace: {{ .Values.configuration.general.veleroNamespace }}
  labels:
    {{- include "velero-ui.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources:
      - pods/log
      - pods/status
      - pods
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "velero.io" ]
    resources: [ "*" ]
    verbs:
      - "*"
{{- end }}
