{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "velero-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "velero-ui.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "velero-ui.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "velero-ui.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "velero-ui.fullname" . }}
  namespace: {{ .Values.configuration.general.veleroNamespace }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "velero-ui.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "velero-ui.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
