apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-ui
rules:
  - apiGroups: [ "" ]
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups: ["velero.io"]
    resources: ["*"]
    verbs:
      - "*"
