apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-ui
subjects:
  - kind: ServiceAccount
    namespace: velero-ui
    name: velero-ui
roleRef:
  kind: ClusterRole
  name: velero-ui
  apiGroup: rbac.authorization.k8s.io
