apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-ui
  namespace: velero-ui
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
    - "secrets"
  verbs:
    - "get"
    - "watch"
    - "list"
- apiGroups:
    - "velero.io"
  resources:
    - "*"
  verbs:
    - "*"
