name: Build and deploy

on:
  push:
    branches:
      - main
    # paths:
    #  - apps/**
    #  - libs/**

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read


env:
  DOCKER_IMAGE: otwld/velero-ui
  NX_BASE: main

jobs:
  main:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3

      # - run: npx nx-cloud record -- nx format:check
      - run: yarn nx run-many -t build --prod

      - run: ls -lr dist/apps


      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - run: echo ${{ steps.package-version.outputs.current-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name:  Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.package-version.outputs.current-version }}, ${{ env.DOCKER_IMAGE }}:latest

