name: Lint, test and build

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    paths:
      - apps/**
      - libs/**

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read


env:
  NX_BASE: main

jobs:
  main:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3

      - run: git branch --track main origin/main
      # - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint build
